### ISSUE TITLE
Building the docker container from the Dockerfile in this repo, throws ReferenceError: globalThis is not defined, when attempting to install crystal.

### ISSUE THREAD

**Issue by ypanagis** [ELTE-DH/NoSketch-Engine-Docker#15]
I was trying to run `docker build` at a local clone of this repo, and the building process throws some errors at `scss` scripts (I see mainly a sequence of `ReferenceError: globalThis is not defined`, ending with:

```ERROR: executor failed running [/bin/sh -c sed  -i 's/npm install/npm install --unsafe-perm=true/' crystal*/Makefile &&     cp page-dashboard.tag crystal*/app/src/dashboard/page-dashboard.tag &&     cd crystal-* &&     make &&     make install VERSION=2.130.1 &&     sed -i 's|URL_BONITO: "http://.*|URL_BONITO: window.location.origin + "/bonito/run.cgi/",|'         /var/www/crystal/config.js]: exit code: 2```.

I am attaching the output of the `docker build` command. Building was tried in both MacOS and Ubuntu Linux, with the same results.

[docker build output](https://github.com/ELTE-DH/NoSketch-Engine-Docker/files/11308639/build.log)

**Comment by dlazesz** [comment]
Reference: https://groups.google.com/a/sketchengine.co.uk/g/noske/c/BvdHnvNTdI8

I'll update the repo soon.

**Comment by dlazesz** [comment]
Fixed in a3560251297f324b31abb873d4d7b7312310021d (v6.0.0)

Please reopen if problem persists.
