### ISSUE TITLE
Update bonito-open to 5.66.3

### ISSUE THREAD

**Issue by Querela** [ELTE-DH/NoSketch-Engine-Docker#16]
The NoSketchEngine `bonito-open` software package has a new release: [`5.66.3`](https://corpora.fi.muni.cz/noske/current/src/bonito-open-5.66.3.tar.gz). You should update since version [`5.63.9`](https://github.com/ELTE-DH/NoSketch-Engine-Docker/blob/main/noske_files/bonito-open-5.63.9.tar.gz) has a security vulnerability that has been fixed in the current version.

Otherwise thanks for open sourcing this repo, it was a great help to setup our own deployment. (will be open sourced soon)

**Comment by dlazesz** [comment]
Thank you! The new release is out.
