### ISSUE TITLE
make execute CMD does not allow multiple arguments

### ISSUE THREAD

**Issue by ValRCS** [ELTE-DH/NoSketch-Engine-Docker#17]
### Problem:
`make execute CMD="compilecorp --no-ske --recompile-corpus CORPUS_REGISTRY_FILE"` does not work due to the way Docker passes arguments to container shell

You get command not found error:
`/usr/local/bin/entrypoint.sh: line 42: compilecorp --no-ske --recompile-corpus CORPUS_REGISTRY_FILE: command not found
make: *** [Makefile:77: execute] Error 127`

Similar errors would be for any shell command with arguments such as `make execute CMD="ls -a"` while `make execute CMD="ls"` works fine.

Note: `make compile` - works fine for compiling all corpora 

### Workaround:

Simply run the docker command directly on a running container without make

`docker exec noske compilecorp --no-ske --recompile-corpus CORPUS_REGISTRY_FILE` 

### Configuration:

This is on: 
* Docker version 25.0.3, build 4debf41
* Ubuntu 22.04.4 LTS
* CORPUS_REGISTRY_FILE is actually my_corpus_registry_file in /corpora/registry folder
* /corpora/my_corpus/vertical/my_corpus.vert holds that particular corpus

### Possible solution

There are solutions involving creating my_script.sh files for passthrough
https://stackoverflow.com/questions/32727594/how-to-pass-arguments-to-shell-script-through-docker-run

PS Fantastic work on this container!

**Comment by dlazesz** [comment]
Thank you for pointing this issue out!
I'm glad that you find this container useful!

I've commited a one-liner to fix it: bfbed05. No need to rebuild the docker image, just pull the new commit or apply the patch manually.

On my machine all the above examples worked, so I close this issue as fixed.
Please repoen if you find some corner case that may not work.
