### ISSUE TITLE
How to change the Web UI language?

### ISSUE THREAD

**Issue by fishfree** [ELTE-DH/NoSketch-Engine-Docker#21]
In the container, there is a file `/var/www/crystal/locale/zh_Hans.json` (confusingly, in the web UI, right-up corner, account->settings->language, there is no Chinese options.), then I change this line to `DEFAULT_LOCALE: "zh_Hans"`, in the file `/var/www/crystal/config.js`, However, it does not take effect after refreshing the page. 

I also asked here, the said file `localization.meta.js` cannot be found in the container.

**Comment by dlazesz** [comment]
[The container is to be run from an image, which is to be build and not modified later](https://stackoverflow.com/questions/23735149/what-is-the-difference-between-a-docker-image-and-a-container). To add language you must modify the [build script](https://github.com/ELTE-DH/NoSketch-Engine-Docker/blob/main/Dockerfile). The file you mention is in [noske_files](https://github.com/ELTE-DH/NoSketch-Engine-Docker/tree/main/noske_files) directory in the crystal-open-*.tar.gz compressed archive file which is identical to the one found at: [https://nlp.fi.muni.cz/trac/noske/wiki/WikiStart#Lateststablerelease](https://nlp.fi.muni.cz/trac/noske/wiki/WikiStart#Lateststablerelease)

- In it you can find __/app/locale/__ directory  which contains the localisation files.
- In the same archive file in __/app/src/core/Meta/__ directory you can find the mentioned __Localization.meta.js__.

It is up to you to change the build script to accommodate your changes. Then you need to rebuild the image and run the container for the changes to take effect.

**Comment by fishfree** [comment]
@dlazesz Thank you very much!
