### ISSUE TITLE
How to access the API?

### ISSUE THREAD

**Issue by fishfree** [ELTE-DH/NoSketch-Engine-Docker#22]
I asked a related question [here](https://groups.google.com/a/sketchengine.co.uk/g/noske/c/9zj7Uu-8nZo). But I tried to access http://****:10070/search/corp_info, it shows 404 Not  Found.

Or even should we firstly enable the API funtionality? If so, how to do?

**Comment by dlazesz** [comment]
In the case of this repo the base URL is: __http://****:10070/bonito/run.cgi__

For example: __http://****:10070/bonito/run.cgi/wordlist?corpname=susanne&wlattr=word&wlpat=test.*&wlsort=frq&wlmaxitems=2&format=json__

Should yield:

```
{"new_maxitems": 2, "wllimit": 0, "total": 4, "totalfrq": 52, "lastpage": 0, "Items": [{"str": "test", "frq": 26, "relfreq": 172.84246}, {"str": "tested", "frq": 13, "relfreq": 86.42123}], "wlattr_label": "word", "frtp": "frequency", "api_version": "open-5.71.15", "manatee_version": "2.36.7-open-2.225.8", "request": {"wlmaxitems": "2", "wlpat": "test.*", "format": "json", "corpname": "susanne", "wlsort": "frq", "wlattr": "word"}}
```

No further step should be made.

**Comment by fishfree** [comment]
@dlazesz Thank you very much!
